Reacttry - restored missing files to react version
rchain-community/liquid-democracy pull request #38
Opened 2021-03-02 23:40 UTC by jimscarver

2021-03-03 02:21 UTC, dckc commented
This still deletes and re-creates files. Please stop using commit 564e09248c64b211ca9a73ac9ef1500ce2e8597f . Go back to master and commit from there.

Please review your diffs when you commit and write a commit message that corresponds to the diffs. If you're deleting a file, the commit message should be clear about why.

2021-03-03 02:40 UTC, jimscarver commented
I cannot make all the changes tobi make from master. I did what I thought you told me to do.

2021-03-03 02:58 UTC, jimscarver commented
the diffs do not show the files deleted  or restored as far as I can see in the diffs. Some files are deleted because I failed to replace them believing they were not in use. I re added Ballot.js so I guess I lost history on that. Perhaps that can be readded properly by you dan?

2021-03-03 03:55 UTC, dckc commented
> the diffs do not show the files deleted or restored as far as I can see in the diffs.

I mean the diffs to each commit. The message for each commit should match the diffs for each commit.

> ... Perhaps that can be readded properly by you dan?

I went ahead and did what I suggested:
  - check out master in one directory, the react branch in another
  - copy files from the react director to the master directory
  - commit the results to a new branch
    - well, I re-used the branch name `reacttry` to go with this pull request.
    - the previous contents of reacttry, c8e336d, are available as reacttry-oops

I'm still not ready to merge; I'll comment separately.

2021-03-03 04:06 UTC, dckc requested changes
Without instruction on how to run it, I can't evaluate this further.

I tried `yarn install; yarn start` but I got:

```
SyntaxError: /tmp/ld-master/jsconfig.json: Unexpected token / in JSON at position 0
```

2021-03-03 04:06 UTC, dckc commented on package.json
> +  "description": "A template for building your dApp. Execute rholang code on the rchain network in real time.",
Please fix the description.

2021-03-03 04:06 UTC, dckc commented on package.json
> -  "eslint": {
Why delete the eslint rules? I should have documented the project style in CONTRIBUTING.md as well, but I'd like this project to match agoric / airbnb style.

2021-03-03 04:06 UTC, dckc commented on package.json
> -    "Dan Connolly"
Taking our names out of the contributors list is extremely un-cool.

2021-03-03 04:06 UTC, dckc commented on package.json
> -    "lint:types": "tsc -p jsconfig.json",
The lint:types rule is important, along with lint-fix and lint-check. Why were they removed?

2021-03-03 04:06 UTC, dckc commented on public/index.html
> +</html>
newline missing at end of file

2021-03-03 07:11 UTC, dckc commented
ok... I got it running, after removing comments and trailing commas from `jsconfig.json`. I hope we can get whatever is tripping over those to ignore that file; it's annoying to lose comments. But I guess they're not criticial.

The README should say how to start it, though `yarn; yarn start` is sufficiently widely known that it's not critical at this stage.

2021-03-03 07:18 UTC, dckc commented
@9rb the snyk thing is making noise again. The Details link goes to something that I don't have access to.

As I [previously asked][1], please turn it off.

[1]: https://github.com/rchain-community/rchain-api/pull/83#issuecomment-786342584

2021-03-03 07:37 UTC, dckc commented
Is the UI interestingly different with react? The main difference I saw was a bunch more text that made the main widgets further down the page.

If we're going to switch UI libraries, perhaps this PR should add something that show off the difference?

I'm not sure I want to take on the risk of **30x dependencies**. It's _much_ slower to start up.

excluding devDependencies (`npm install --only=prod`) comparing bloat vs master...

|             | deps | size |
|-----------| ------ | ------ |
| master  | 118  | 44M |
| react  |  3429 | 281M |

```
$ du -sh node_modules/
281M	node_modules/

$ npm ls | wc -l
3429
```



```
$ du -sh node_modules/
44M	node_modules/

$ npm ls | wc -l
118
```

2021-03-22 15:24 UTC, jimscarver commented
the react overhead is quite high and without much benefit..

2021-03-22 15:24 UTC, closed without merging